name: com_kaandikec_snihostchecker
description: "SNI bug host finder App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2  # Updated to a valid version
  file_picker: ^5.0.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  win32: ^2.0.0
  sqflite_common_ffi: ^2.0.0+1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
