name: Windows Release CI

on:
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.19.3"

      - name: Clean project
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Check Flutter Version
        run: flutter --version

      # Enable Windows Desktop Support
      - name: Enable Windows Desktop Support
        run: flutter config --enable-windows-desktop

      # Build release EXE for Windows with verbose logging
      - name: Build Windows EXE
        run: flutter build windows --release

      # List build directory to debug the output path
      - name: List build directory
        run: dir build\windows\x64\runner\Release

      # Upload all files in the Release directory including data folder and DLL
      - name: Upload release files
        uses: actions/upload-artifact@v3
        with:
          name: release-files
          path: build/windows/x64/runner/Release
